# Modèle objet numpy

In [1]:
import numpy as np

In [3]:
t = np.random.normal(10, 4, 1000)
t

array([ 1.25703446e+01,  6.71745443e+00,  4.00355590e+00,  1.83442746e+01,
        9.68224971e+00,  3.14145882e+00,  1.07776952e+01,  3.86227411e+00,
        9.31171441e+00,  5.73946432e+00,  4.35409250e+00,  1.26277585e+01,
        1.00237277e+01,  1.39624021e+01,  4.77233031e+00,  1.53459055e+01,
        5.49908581e+00,  1.02823650e+01,  7.59364736e+00,  1.58171599e+01,
        5.90842644e+00,  1.22054232e+01,  6.08377968e+00,  1.12484210e+01,
        1.09685178e+01,  1.66822653e+01,  8.43096643e+00,  1.59056912e+01,
        5.06197208e+00,  4.83135723e+00,  1.33556290e+01,  1.21434434e+01,
        9.16814764e+00,  8.86408958e+00,  7.30301421e+00,  8.21485732e+00,
        9.23886960e+00,  1.34341155e+01,  1.23530179e+01,  1.22504830e+01,
        4.01684167e+00,  9.32032190e+00,  1.14899736e+01,  1.49022918e+01,
        4.93731851e+00,  8.33895906e+00,  2.62040482e+00,  3.02827456e+00,
        4.04681823e+00,  1.29563783e+01,  1.36314150e+01,  6.25833805e+00,
        1.88042853e+01,  

In [8]:
def info(t: np.ndarray):
    print(type(t))
    print(t.shape)
    print(t.dtype)
    print(t.flags)

In [9]:
info(t)

<class 'numpy.ndarray'>
(1000,)
float64
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [7]:
t2 = t.reshape((20,50))
t2

array([[ 1.25703446e+01,  6.71745443e+00,  4.00355590e+00,
         1.83442746e+01,  9.68224971e+00,  3.14145882e+00,
         1.07776952e+01,  3.86227411e+00,  9.31171441e+00,
         5.73946432e+00,  4.35409250e+00,  1.26277585e+01,
         1.00237277e+01,  1.39624021e+01,  4.77233031e+00,
         1.53459055e+01,  5.49908581e+00,  1.02823650e+01,
         7.59364736e+00,  1.58171599e+01,  5.90842644e+00,
         1.22054232e+01,  6.08377968e+00,  1.12484210e+01,
         1.09685178e+01,  1.66822653e+01,  8.43096643e+00,
         1.59056912e+01,  5.06197208e+00,  4.83135723e+00,
         1.33556290e+01,  1.21434434e+01,  9.16814764e+00,
         8.86408958e+00,  7.30301421e+00,  8.21485732e+00,
         9.23886960e+00,  1.34341155e+01,  1.23530179e+01,
         1.22504830e+01,  4.01684167e+00,  9.32032190e+00,
         1.14899736e+01,  1.49022918e+01,  4.93731851e+00,
         8.33895906e+00,  2.62040482e+00,  3.02827456e+00,
         4.04681823e+00,  1.29563783e+01],
       [ 1.36

In [10]:
info(t2)

<class 'numpy.ndarray'>
(20, 50)
float64
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [12]:
print(t[0])
print(t2[0,0])

12.570344575321515
12.570344575321515


In [13]:
t[0] = 13.5
print(t[0])
print(t2[0,0])

13.5
13.5


In [14]:
t2[0] = 13
print(t[0])
print(t2[0,0])

13.0
13.0


In [16]:
info(t2.T)

<class 'numpy.ndarray'>
(50, 20)
float64
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [17]:
t2.T[3,4] = 15.5
print(t2.T[3,4])
print(t2[4,3])
print(t[203])

15.5
15.5
15.5


## Properties

In [19]:
# ndarray is protected: no attribute can be added
# AttributeError: 'numpy.ndarray' object has no attribute 'toto'
# t.toto = 3

In [24]:
class Dummy:
    pass

d = Dummy()
d.toto = 3
print(d.toto)
d.toto = 5.5
print(d.toto)
d.toto = "toto"
print(d.toto)
d.toto = lambda x: x**2+1
print(d.toto)
print(d.toto(3))
del d.toto
print(d.toto)

3
5.5
toto
<function <lambda> at 0x0000029CCE48D1F0>
10


AttributeError: 'Dummy' object has no attribute 'toto'

In [25]:
t2.shape = (10, 100)
info(t2)

<class 'numpy.ndarray'>
(10, 100)
float64
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [27]:
# setter protects bad usage
try:
    t2.shape = (100, 100)
except ValueError as e:
    print("ValueError:", e)

ValueError: cannot reshape array of size 1000 into shape (100,100)


In [28]:
# # AttributeError: attribute 'flags' of 'numpy.ndarray' objects is not writable
# del t2.flags

AttributeError: attribute 'flags' of 'numpy.ndarray' objects is not writable

## Héritage

In [30]:
print(t2.min())
t2[t2<0]

-0.8566728496229867


array([-0.85667285, -0.67929233, -0.00930838])

In [31]:
t3 = np.ma.masked_less(t2, 0)
t3

masked_array(
  data=[[13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0,
         13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0,
         13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0,
         13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0,
         13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 13.0,
         13.6314150156925, 6.258338049865151, 18.804285320543393,
         6.208299913039038, 11.842299286275484, 8.095138096772988,
         13.35518206521495, 12.794339264546073, 6.887339407303914,
         8.27992617985226, 9.284022622594119, 5.491922848564069,
         8.476889613020223, 6.352941994168242, 8.832948449186414,
         7.950532496692043, 10.32440478135513, 7.4173018615014294,
         8.412299480557973, 13.845548088920683, 2.0022592480040657,
         10.16741037212617, 15.055206072366403, 8.97702905209655,
         15.171880958669766, 13.697550526960352, 13.335454586060271,
         6.884884396261015, 16.699624657

In [33]:
# class MaskedArray inherits from ndarray
assert isinstance(t3, np.ndarray)
assert isinstance(t3, np.ma.MaskedArray)

In [34]:
print("min:",t2.min(),"mean:", t2.mean())
print("min:",t3.min(),"mean:", t3.mean())

min: -0.8566728496229867 mean: 10.355803019692972
min: 0.145379231950864 mean: 10.388513834759387


## Builtins operators and functions

In [37]:
r = t2 + 5
print(r[:3,:3])
r = 5 + t2
print(r[:3,:3])
r += 2
print(r[:3,:3])

[[18.         18.         18.        ]
 [11.40579895 16.77014544 17.97210784]
 [14.75281804 15.6931494  18.21901887]]
[[18.         18.         18.        ]
 [11.40579895 16.77014544 17.97210784]
 [14.75281804 15.6931494  18.21901887]]
[[20.         20.         20.        ]
 [13.40579895 18.77014544 19.97210784]
 [16.75281804 17.6931494  20.21901887]]


In [39]:
r = t2 - 5 # ndarray.__sub__ => result
print(r[:3,:3])
r = 5 - t2 # int.__sub__ => NotImplemented, ndarray.__rsub__ = result
print(r[:3,:3])
r -= 2
print(r[:3,:3])

[[8.         8.         8.        ]
 [1.40579895 6.77014544 7.97210784]
 [4.75281804 5.6931494  8.21901887]]
[[-8.         -8.         -8.        ]
 [-1.40579895 -6.77014544 -7.97210784]
 [-4.75281804 -5.6931494  -8.21901887]]
[[-10.         -10.         -10.        ]
 [ -3.40579895  -8.77014544  -9.97210784]
 [ -6.75281804  -7.6931494  -10.21901887]]


In [44]:
# if both LeftType.__add__ and RightType.__radd__ are NotImplemented => exception
# TypeError: unsupported operand type(s) for +: 'Dummy' and 'int'
# Dummy() + 5

In [46]:
assert '__len__' in dir(np.ndarray)
len(t)  # => __len__

1000

In [47]:
t2 < 0 # => __lt__

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fals

In [48]:
print(t2[:3,:3]) # => str(t2..) => __str__
t2[:3,:3] # repr(t2...) => __repr__

[[13.         13.         13.        ]
 [ 6.40579895 11.77014544 12.97210784]
 [ 9.75281804 10.6931494  13.21901887]]


array([[13.        , 13.        , 13.        ],
       [ 6.40579895, 11.77014544, 12.97210784],
       [ 9.75281804, 10.6931494 , 13.21901887]])